version: "3.8"
services:

  db:
    image: postgres:11
    ports:
      - "5432:5432"
    command: postgres -c ssl=off
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_multi

  pgadmin:
    container_name: pgadmin_invoicejet-api
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db