"""empty message

Revision ID: 76f1614a6597
Revises: ee3945f68741
Create Date: 2022-10-10 11:59:09.712521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f1614a6597'
down_revision = 'ee3945f68741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_business_user_id_user', 'business', type_='foreignkey')
    op.create_foreign_key(op.f('fk_business_user_id_user'), 'business', 'user', ['user_id'], ['id'], source_schema='app', referent_schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_business_user_id_user'), 'business', schema='app', type_='foreignkey')
    op.create_foreign_key('fk_business_user_id_user', 'business', 'user', ['user_id'], ['id'], referent_schema='core')
    # ### end Alembic commands ###
