"""empty message

Revision ID: ee3945f68741
Revises: 
Create Date: 2022-10-10 11:58:31.962807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3945f68741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.user.id'], name=op.f('fk_business_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business')),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business', schema='app')
    # ### end Alembic commands ###
