"""empty message

Revision ID: 210e3bbc5e8a
Revises: 
Create Date: 2022-10-10 11:58:26.193264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210e3bbc5e8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='core')
    # ### end Alembic commands ###
